version: '3.8'
services:

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports:
      - "8080:80"

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    tty: true
    command: sleep infinity

  wazuh:
    image: wazuh/wazuh
    container_name: wazuh
    ports:
      - "1514:1514/udp"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec/data

volumes:
  wazuh_data:
